---
# Site settings
site_name: Conference
site_url: https://pioneershub.github.io/conference/
site_author: Alexander Hendorf
site_description: >-
  Template for organizing a volunteer-driven conference.

# Repository at GitHub
repo_name: PioneersHub/conference
repo_url: https://github.com/PioneersHub/conference

# Copyright for footer
copyright:
  start_year: 2024
  owner: Pioneers Hub gGmbH

# Event details
event:
  event_name: "THE EVENT"
  start_date: "23.04.2025"
  end_date: "25.04.2025"
  day_before: "22.04.2025"
  month: "April"
  year: "2025"
  location: "Somewhere, Germany"
  apply_url: "https://example.com/apply"
  contact_email: "info@contact.org"
  cfp_open: "01.01.2025"
  cfp_close: "01.02.2025"
  review_deadline: "15.02.2025"
  cfp_speakers_notifications: "01.03.2025"
  cfp_link: "https://pretlax.com/"
  voting_url: "https://pretlax.com/"
  voting_start: "02.02.2025 12:00 CET"
  voting_end: "15.25.2025 23:59 CET"
  contact_program: "https://pycon.de/"
  financial_aid_open: "01.01.2025"
  financial_aid_close: "01.02.2025"
  financial_aid_notifications: "01.03.2025"
  call_for_committee_open: "01.10.2024"
  call_for_committee_close: "01.11.2024"
  call_for_volunteers_open: "01.01.2025"
  call_for_volunteers_close: "01.02.2025"
  ticket_sales_open: "01.01.2025"
  ticket_sales_late_bird: "01.03.2025"

  # Code of Conduct Team
  coc_email: coc-reports@our-community.org
  team_members: |
    - Avery Sinclair
    - Morgan Ellis
    - Rowan Bennett
    - Taylor Monroe
  backup_team_members: |
    - Jordan Reese email@domain.com
    - Casey Whitman email@domain.com

committees:
  # Committee names must match the headers in the committees.md file
  # Expected workloads and milestones for each committee
  "coc":
    requirements:
      attend_conference: true
    workload:
      start: "start-date-here"
      peak: "During the conference"
      end: "Until all reports have been resolved"
  "communication":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "diversity":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "experience":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "infrastructure":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "on_site_experience":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "on_site_operations":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "program":
    attend_conference: false
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "remote_experience":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "steering":
    attend_conference: true
    workload:
      start: "Ten hours per week during review and selection (3-4 weeks)."
      peak: "6 months before the conference until the conference."
      end: "end-date-here"
  "swag":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "video":
    attend_conference: true
    workload:
      start: "start-date-here"
      peak: "During the conference"
      end: "Until all videos have been released"

# custom config for social cards customisation
social_cards:
  dirs:
    # relative paths from the repository root
    cache_dir: "./.cache/plugin/social"
    site_dir: "./site/assets/images/social"
    # convention, rename your logo accordingly
  logo_path: "./docs/assets/images/social_card_logo.png"
